### ISSUE TITLE
Typescript alias

### ISSUE THREAD

**Issue by janosh** [pre-commit/identify#377]
What's the state of #29?

I currently have to set types inconsistently:

```yml
      - id: no-repeated-whitespace
        name: No repeated spaces
        entry: '\S+\s{2,}'
        language: pygrep
        types: [text]
        exclude_types: [javascript, ts] # works

      - id: foo
        name: foo
        entry: '\S+\s{2,}'
        language: pygrep
        exclude_types: [js, ts] # broken

      - id: bar
        name: bar
        entry: '\S+\s{2,}'
        language: pygrep
        exclude_types: [javascript, typescript] # broken
```

Valid values:

> Value is not accepted. Valid values: "adobe-illustrator", "alpm", "apinotes", "asar", "asciidoc", "ash", "asm", "aspectj", "audio", "avif", "awk", "babelrc", "bash", "batch", "bats", "bazel", "bazelrc", "bib", "binary", "bitmap", "bowerrc", "browserslistrc", "bzip2", "c", "c#", "c++", "c2hs", "cbsd", "clojure", "clojurescript", "cmake", "codespellrc", "coffee", "coveragerc", "crystal", "csh", "cson", "csproj", "css", "csslintrc", "csv", "cuda", "cython", "dart", "dash", "def", "diff", "directory", "dockerfile", "dockerignore", "dotenv", "dtd", "editorconfig", "edn", "ejs", "eot", "eps", "erb", "executable", "expect", "file", "fish", "flake8", "gdscript", "geojson", "gherkin", "gif", "gitattributes", "gitconfig", "gitignore", "gitlint", "gitmodules", "go", "go-mod", "go-sum", "gotmpl", "gpx", "graphql", "groovy", "gyb", "gyp", "gzip", "handlebars", "haskell", "hcl", "header", "hgrc", "html", "icalendar", "icns", "icon", "idl", "idris", "image", "inc", "ini", "inl", "ino", "inx", "jade", "jar", "java", "java-properties", "javascript", "jenkins", "jinja", "jpeg", "jshintrc", "json", "json5", "jsonnet", "jsx", "jupyter", "kml", "kotlin", "ksh", "lean", "lektor", "lektorproject", "less", "liquid", "literate-haskell", "lua", "mailmap", "makefile", "manifest", "map", "markdown", "mdx", "mention-bot", "mib", "modulemap", "musescore", "myst", "ngdoc", "nim", "nimble", "nix", "non-executable", "npmignore", "nunjucks", "objective-c", "objective-c++", "ocaml", "otf", "p12", "pdbrc", "pdf", "pem", "perl", "php", "pkgbuild", "plain-text", "plantuml", "plist", "png", "pofile", "powershell", "prettierignore", "prisma", "proto", "puppet", "purescript", "pyi", "pylintrc", "pypirc", "pyproj", "python", "python2", "python3", "pyz", "qml", "r", "relax-ng", "rst", "ruby", "rust", "salt", "sass", "sbt", "scala", "scheme", "scss", "sh", "shell", "sln", "socket", "solidity", "spec", "sql", "stylus", "svelte", "svg", "swf", "swift", "swiftdeps", "symlink", "system-verilog", "tar", "tcsh", "terraform", "tex", "text", "thrift", "tiff", "toml", "ts", "tsv", "tsx", "ttf", "twig", "twisted", "txsprofile", "urdf", "vb", "vbproj", "vcxproj", "vdx", "verilog", "vhdl", "vim", "vtl", "vue", "wav", "webp", "wheel", "wkt", "woff", "woff2", "wsgi", "xhtml", "xml", "xquery", "xsd", "xsl", "yaml", "yamllint", "yang", "yin", "zcml", "zig", "zip", "zpt", "zsh".yaml-schema: .pre-commit-config.yml(1)
